
sudo: required
services:
    - docker

before_install:
    - docker build -t scramsay/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true scramsay/react-test npm test

after_success:
    - docker build -t scramsay/multi-client ./client
    - docker build -t scramsay/multi-nginx ./nginx
    - docker build -t scramsay/multi-server ./server
    - docker build -t scramsay/multi-worker ./worker
    # Log in to the docker CLI (env vars on travis-ci).
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take images and push them to docker hub (scramsay is public repo).
    - docker push scramsay/multi-client
    - docker push scramsay/multi-nginx
    - docker push scramsay/multi-server
    - docker push scramsay/multi-worker

language: generic

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker2
    env: MultiDocker2-env
    bucket_name: elasticbeanstalk-us-east-1-657749227937
    bucket_path: multi-docker2
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
